version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - build_cache:/build
    tmpfs:
      # Mount the ember-cli tmp directory as a tmpfs partition for better
      # performance.
      - /app/src/api-umbrella/admin-ui/tmp:rw,size=128m,mode=1777
    environment:
      HTTP_PORT: 8888
      HTTPS_PORT: 8443
    ports:
      - "8888:8888"
      - "8443:8443"
    networks:
      main:
        aliases:
          - umbrella2.docker

networks: 
  main:
    external: true

volumes:
  build_cache:
